export const colors = {
  donorBackground: '#ed5555',
  donorHoverActive: '#eb3e3e',
  donorFocus: '#de1818',
  npoBackground: '#065ef5',
  npoHoverActive: '#0554dc',
  npoFocus: '#0441aa',
  calendarSelectedBackground: '#4db6ac',
  calendarSelectedHoverActive: '#35ada0',
  calendarSelectedFocus: '#16a595',
  calendarUnselectedBackground: '#ffffff',
  calendarUnselectedHoverActiveFocus: '#e7e7e7',
  subtleGrey: '#707070', // used in view all button's border, footer description of donation cards
  loginBackground: '#212121',
  loginHoverActive: '#424242',
  loginFocus: '#616161',
  categoryTagsFill: '#D9D9D9',
  bump: '#4db6ac',
  seeMoreHoverFocusActive: '#e7e7e7',
  editProfileButtonBackground: '#43aad8',
  editProfileButtonHoverActive: '#31A2D6',
  editProfileButtonFocus: '#138CC8',
  verifiedIconBackground: '#57A4FF',
  chatButtonBackground: '#43aad8',
  chatButtonHoverActive: '#31A2D6',
  chatButtonFocus: '#138CC8',
  ratingStarBackground: '#ED5555',
};
