export const WISHES_COLLECTION = {
  wishId: 'wishId',
  postedDateTime: 'postedDateTime',
  updatedDateTime: 'updatedDateTime',
  title: 'title',
  status: 'status',
  description: 'description',
  categories: 'categories',
  locations: 'locations',
  user: 'users',
  organization: 'organization',
  closed: 'closed',
  completed: 'completed',
  lastActionByUserDateTime: 'lastActionByUserDateTime',
  expireDateTime: 'expireDateTime',
  event: 'event',
  isBumped: 'isBumped',
  isDisabled: 'isDisabled',
};
