export const dummyTopCategoriesAndTheirDonations = [
  {
    id: '3ZurlkyhxGG6jYiuzoKB',
    imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842156/dailynecessities.jpg',
    iconUrl: 'dailynecessities_icon',
    name: 'Daily Necessities',
    donations: [
      {
        description: 'A few families need tissues as they are sold out.',
        title: 'Need tissues',
        user: {
          userId: 'MjLPFPmRhaH5WKYRloTr',
          profileImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1589378414/profile.jpg',
          userName: 'jamessspanggg',
        },
        updatedDateTime: 1589385600000,
        donationId: 'pbLFnOBA7gi8ZhTo7T3l',
        isBumped: false,
        expireDateTime: 1589990400000,
        lastActionByUserDateTime: 1589385600000,
        status: 'pending',
        postedDateTime: 1589385600000,
        coverImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842156/dailynecessities.jpg',
        categories: [
          {
            imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842156/dailynecessities.jpg',
            iconUrl: 'dailynecessities_icon',
            name: 'Daily Necessities',
            id: '3ZurlkyhxGG6jYiuzoKB',
          },
        ],
      },
      {
        description: 'Ran out of cooking oil to cook.',
        title: 'Need cooking oil',
        user: {
          userId: 'MjLPFPmRhaH5WKYRloTr',
          profileImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1589378414/profile.jpg',
          userName: 'jamessspanggg',
        },
        updatedDateTime: 1589385600000,
        donationId: 'pbLFnOBA7gi8ZhTo7T3l',
        isBumped: false,
        expireDateTime: 1589990400000,
        lastActionByUserDateTime: 1589385600000,
        status: 'pending',
        postedDateTime: 1589385600000,
        coverImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842156/dailynecessities.jpg',
        categories: [
          {
            imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842156/dailynecessities.jpg',
            iconUrl: 'dailynecessities_icon',
            name: 'Daily Necessities',
            id: '3ZurlkyhxGG6jYiuzoKB',
          },
        ],
      },
      {
        description: 'Ran out of cooking oil to cook.',
        title: 'Need cooking oil',
        user: {
          userId: 'MjLPFPmRhaH5WKYRloTr',
          profileImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1589378414/profile.jpg',
          userName: 'jamessspanggg',
        },
        updatedDateTime: 1589385600000,
        donationId: 'pbLFnOBA7gi8ZhTo7T3l',
        isBumped: false,
        expireDateTime: 1589990400000,
        lastActionByUserDateTime: 1589385600000,
        status: 'pending',
        postedDateTime: 1589385600000,
        coverImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842156/dailynecessities.jpg',
        categories: [
          {
            imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842156/dailynecessities.jpg',
            iconUrl: 'dailynecessities_icon',
            name: 'Daily Necessities',
            id: '3ZurlkyhxGG6jYiuzoKB',
          },
        ],
      },
      {
        lastActionByUserDateTime: 1589216362124,
        postedDateTime: 1589216362124,
        status: 'pending',
        categories: [
          {
            iconUrl: 'food_icon',
            name: 'Food',
            id: 'LokORpW2MEKJx1ayG3h6',
            imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842129/food.jpg',
          },
          {
            id: '3ZurlkyhxGG6jYiuzoKB',
            imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842156/dailynecessities.jpg',
            iconUrl: 'dailynecessities_icon',
            name: 'Daily Necessities',
          },
        ],
        coverImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842156/dailynecessities.jpg',
        description: 'Tamago',
        title: 'Eggs Supplies',
        user: {
          userId: '5oBhU2SGiKEKOzNLa2zt',
          profileImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1589378414/profile.jpg',
          userName: 'hello world',
        },
        updatedDateTime: 1589216362124,
        donationsId: 'OJxYnK5jhQrG1quNg08y',
        expireDateTime: 1591894762124,
        isBumped: false,
      },
      {
        lastActionByUserDateTime: 1589216362124,
        postedDateTime: 1589216362124,
        status: 'pending',
        categories: [
          {
            iconUrl: 'food_icon',
            name: 'Food',
            id: 'LokORpW2MEKJx1ayG3h6',
            imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842129/food.jpg',
          },
          {
            id: '3ZurlkyhxGG6jYiuzoKB',
            imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842156/dailynecessities.jpg',
            iconUrl: 'dailynecessities_icon',
            name: 'Daily Necessities',
          },
        ],
        coverImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842156/dailynecessities.jpg',
        description: "This circuit breaker is killing me, I can't have my favourite fried chicken!!!",
        title: 'Fried Chicken Needed ASAP',
        user: {
          userId: '5oBhU2SGiKEKOzNLa2zt',
          profileImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1589378414/profile.jpg',
          userName: 'hello world',
        },
        updatedDateTime: 1589216362124,
        donationId: 'OJxYnK5jhQrG1quNg08y',
        expireDateTime: 1591894762124,
        isBumped: false,
      },
    ],
  },
  {
    imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842198/stationery.jpg',
    iconUrl: 'stationery_icon',
    name: 'Stationery',
    id: '49yM4ELhrrFWr6phmP8d',
    donations: [
      {
        expireDateTime: 1589990400000,
        isBumped: false,
        lastActionByUserDateTime: 1589385600000,
        coverImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842198/stationery.jpg',
        postedDateTime: 1589385600000,
        status: 'pending',
        categories: [
          {
            imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842198/stationery.jpg',
            iconUrl: 'stationery_icon',
            name: 'Stationery',
            id: '49yM4ELhrrFWr6phmP8d',
          },
        ],
        description:
          'Need some books for children for a few families. Especially books about computer science as some of the kids are interested.',
        title: 'Book Supplies',
        user: {
          userName: 'jamessspanggg',
          userId: 'MjLPFPmRhaH5WKYRloTr',
          profileImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1589378414/profile.jpg',
        },
        updatedDateTime: 1589385600000,
        donationId: 'tOrHeSKzxYSGDFiNEuZf',
      },
      {
        expireDateTime: 1589990400000,
        isBumped: false,
        lastActionByUserDateTime: 1589385600000,
        coverImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842198/stationery.jpg',
        postedDateTime: 1589385600000,
        status: 'pending',
        categories: [
          {
            imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588842198/stationery.jpg',
            iconUrl: 'stationery_icon',
            name: 'Stationery',
            id: '49yM4ELhrrFWr6phmP8d',
          },
        ],
        description: 'Pencils and crayons needed for the childrent to do their homework.',
        title: 'Pencils and crayons',
        user: {
          userName: 'jamessspanggg',
          userId: 'MjLPFPmRhaH5WKYRloTr',
          profileImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1589378414/profile.jpg',
        },
        updatedDateTime: 1589385600000,
        donationId: 'tOrHeSKzxYSGDFiNEuZf',
      },
    ],
  },
  {
    imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588838805/toysandgames.jpg',
    iconUrl: 'toysandgames_icon',
    name: 'Toys and Games',
    id: 'GYYRGfzyq67KIj17gVwZ',
    coverImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588838805/toysandgames.jpg',
    donations: [
      {
        expireDateTime: 1589990400000,
        isBumped: false,
        lastActionByUserDateTime: 1589385600000,
        postedDateTime: 1589385600000,
        status: 'pending',
        categories: [
          {
            imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588838805/toysandgames.jpg',
            iconUrl: 'toysandgames_icon',
            name: 'Toys and Games',
            id: 'GYYRGfzyq67KIj17gVwZ',
          },
        ],
        description: "Needs some toys because I'm too bored in jail!",
        title: 'Toys to play',
        user: {
          userName: 'jamessspanggg',
          userId: 'MjLPFPmRhaH5WKYRloTr',
          profileImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1589378414/profile.jpg',
        },
        updatedDateTime: 1589385600000,
        donationId: 'tOrHeSKzxYSGDFiNEuZf',
      },
      {
        expireDateTime: 1589990400000,
        isBumped: false,
        lastActionByUserDateTime: 1589385600000,
        coverImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588838805/toysandgames.jpg',
        postedDateTime: 1589385600000,
        status: 'pending',
        categories: [
          {
            imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588838805/toysandgames.jpg',
            iconUrl: 'toysandgames_icon',
            name: 'Toys and Games',
            id: 'GYYRGfzyq67KIj17gVwZ',
          },
        ],
        description: 'Games needed to provide children with entertainment at home during this period.',
        title: 'Games needed',
        user: {
          userName: 'jamessspanggg',
          userId: 'MjLPFPmRhaH5WKYRloTr',
          profileImageUrl: '',
        },
        updatedDateTime: 1589385600000,
        donationId: 'tOrHeSKzxYSGDFiNEuZf',
      },
      {
        expireDateTime: 1589990400000,
        isBumped: false,
        lastActionByUserDateTime: 1589385600000,
        coverImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588838805/toysandgames.jpg',
        postedDateTime: 1589385600000,
        status: 'pending',
        categories: [
          {
            imageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1588838805/toysandgames.jpg',
            iconUrl: 'toysandgames_icon',
            name: 'Toys and Games',
            id: 'GYYRGfzyq67KIj17gVwZ',
          },
        ],
        description: 'Provide puzzles for old folks home.',
        title: 'Puzzles',
        user: {
          userName: 'jamessspanggg',
          userId: 'MjLPFPmRhaH5WKYRloTr',
          profileImageUrl: 'https://res.cloudinary.com/giftforgood/image/upload/v1589378414/profile.jpg',
        },
        updatedDateTime: 1589385600000,
        donationId: 'tOrHeSKzxYSGDFiNEuZf',
      },
    ],
  },
];
