export const WISHES_BATCH_SIZE = 21;
export const DONATIONS_BATCH_SIZE = 21;
export const REVIEWS_BATCH_SIZE = 10;
export const USER_CHATS_BATCH_SIZE = 20;
export const CHAT_MESSAGES_BATCH_SIZE = 40;
export const NPO_ORGANIZATION_EDIT_HISTORY_BATCH_SIZE = 6;
