name: Lint and Build

on: [pull_request]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Update NPM
        run: npm i -g npm 
      - name: Install packages
        run: npm install 
      - name: Run Prettier 
        run: npm run lint
      - name: Build
        run: npm run build
        env:
          FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
          FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}